<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="FSSCHND13937" ignored="0" name="Default test" tests="12" failures="1" timestamp="18 Jan 2018 14:14:58 GMT" time="29.951" errors="0">
  <testcase name="AccountSync" time="7.965" classname="mBankingControlCenter.MobileBanking"/>
  <testcase name="BalanceEnquiry" time="2.299" classname="mBankingControlCenter.MobileBanking"/>
  <testcase name="CancelMMIDAll" time="3.157" classname="mBankingControlCenter.MobileBanking"/>
  <testcase name="CancelMMIDSingle" time="3.205" classname="mBankingControlCenter.MobileBanking"/>
  <testcase name="ChequeStatus" time="2.429" classname="mBankingControlCenter.MobileBanking"/>
  <testcase name="EmailIDFetch" time="1.187" classname="mBankingControlCenter.MobileBanking"/>
  <testcase name="EmailIDUpdate" time="1.075" classname="mBankingControlCenter.MobileBanking"/>
  <testcase name="GenerateMMID" time="1.565" classname="mBankingControlCenter.MobileBanking"/>
  <testcase name="MiniStatement" time="1.982" classname="mBankingControlCenter.MobileBanking"/>
  <testcase name="RetrieveMMID" time="1.252" classname="mBankingControlCenter.MobileBanking"/>
  <testcase name="StopCheque" time="2.326" classname="mBankingControlCenter.MobileBanking"/>
  <testcase name="TransactionHistory" time="0.378" classname="mBankingControlCenter.MobileBanking">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at mBankingControlCenter.MobileBanking.TransactionHistory(MobileBanking.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TransactionHistory -->
</testsuite> <!-- Default test -->
